<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="8" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-10-28T20:52:09Z" name="Default suite" finished-at="2018-10-28T20:53:10Z" duration-ms="61454">
    <groups>
    </groups>
    <test started-at="2018-10-28T20:52:09Z" name="Default test" finished-at="2018-10-28T20:53:10Z" duration-ms="61454">
      <class name="com.qa.jive.JiveAssignment.CalculatorPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:09Z" name="setup" finished-at="2018-10-28T20:52:26Z" duration-ms="17311" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="refresh()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:26Z" name="refresh" finished-at="2018-10-28T20:52:26Z" duration-ms="217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refresh -->
        <test-method signature="addTwoNumbers()[pri:1, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:26Z" name="addTwoNumbers" description="Add two numbers" finished-at="2018-10-28T20:52:32Z" duration-ms="5885" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addTwoNumbers -->
        <test-method is-config="true" signature="refresh()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:32Z" name="refresh" finished-at="2018-10-28T20:52:32Z" duration-ms="89" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refresh -->
        <test-method signature="subtractTwoNumbers()[pri:2, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:32Z" name="subtractTwoNumbers" description="Subtract two numbers" finished-at="2018-10-28T20:52:38Z" duration-ms="5866" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subtractTwoNumbers -->
        <test-method is-config="true" signature="refresh()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:38Z" name="refresh" finished-at="2018-10-28T20:52:38Z" duration-ms="240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refresh -->
        <test-method signature="multiplyTwoNumbers()[pri:3, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:38Z" name="multiplyTwoNumbers" description="Multiply two numbers" finished-at="2018-10-28T20:52:45Z" duration-ms="6213" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [19781] but found [15131]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [19781] but found [15131]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.qa.jive.JiveAssignment.CalculatorPageTest.multiplyTwoNumbers(CalculatorPageTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multiplyTwoNumbers -->
        <test-method is-config="true" signature="refresh()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:45Z" name="refresh" finished-at="2018-10-28T20:52:45Z" duration-ms="225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refresh -->
        <test-method signature="divideTwoNumbers()[pri:4, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:45Z" name="divideTwoNumbers" description="Divide two numbers" finished-at="2018-10-28T20:52:50Z" duration-ms="5218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divideTwoNumbers -->
        <test-method is-config="true" signature="refresh()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:50Z" name="refresh" finished-at="2018-10-28T20:52:50Z" duration-ms="207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refresh -->
        <test-method signature="divideTwoNumbers2()[pri:5, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:50Z" name="divideTwoNumbers2" description="Divide another set of two numbers" finished-at="2018-10-28T20:52:54Z" duration-ms="3983" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [199]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [199]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.qa.jive.JiveAssignment.CalculatorPageTest.divideTwoNumbers2(CalculatorPageTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divideTwoNumbers2 -->
        <test-method is-config="true" signature="refresh()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:54Z" name="refresh" finished-at="2018-10-28T20:52:55Z" duration-ms="380" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refresh -->
        <test-method signature="backspaceAndAddNumbers()[pri:6, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:52:55Z" name="backspaceAndAddNumbers" description="Backspace and continue to add" finished-at="2018-10-28T20:53:00Z" duration-ms="5441" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- backspaceAndAddNumbers -->
        <test-method is-config="true" signature="refresh()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:53:00Z" name="refresh" finished-at="2018-10-28T20:53:00Z" duration-ms="180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refresh -->
        <test-method signature="invalidOperation()[pri:7, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:53:00Z" name="invalidOperation" description="Invalid operation results in ERR" finished-at="2018-10-28T20:53:01Z" duration-ms="604" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidOperation -->
        <test-method is-config="true" signature="refresh()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:53:01Z" name="refresh" finished-at="2018-10-28T20:53:01Z" duration-ms="313" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refresh -->
        <test-method signature="invalidOperationInfinity()[pri:8, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:53:01Z" name="invalidOperationInfinity" description="Invalid operation results in Infinity" finished-at="2018-10-28T20:53:03Z" duration-ms="1650" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidOperationInfinity -->
        <test-method is-config="true" signature="refresh()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:53:03Z" name="refresh" finished-at="2018-10-28T20:53:03Z" duration-ms="407" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refresh -->
        <test-method signature="invalidOperationNaN()[pri:9, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:53:03Z" name="invalidOperationNaN" description="Invalid operation results in NaN" finished-at="2018-10-28T20:53:05Z" duration-ms="1570" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidOperationNaN -->
        <test-method is-config="true" signature="refresh()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:53:05Z" name="refresh" finished-at="2018-10-28T20:53:05Z" duration-ms="412" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- refresh -->
        <test-method signature="complexOperation()[pri:10, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:53:05Z" name="complexOperation" description="Operator precedence" finished-at="2018-10-28T20:53:10Z" duration-ms="4741" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- complexOperation -->
        <test-method is-config="true" signature="quit()[pri:0, instance:com.qa.jive.JiveAssignment.CalculatorPageTest@62230c58]" started-at="2018-10-28T20:53:10Z" name="quit" finished-at="2018-10-28T20:53:10Z" duration-ms="244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.qa.jive.JiveAssignment.CalculatorPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
